name: CI & CD

on:
  push:
    branches: [main]

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Install pnpm
        uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd

      - name: Use Node.js 18
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Lint code
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck
